import a2DesiCowMilk from "../../img/a2DesiCowMilk.png";
import fullCream from "../../img/fullCream.png";
import tonedMilk from "../../img/tonedMilk.png";
import doubleTonedMilk from "../../img/DTM2.png";
import naturalCowMilk from "../../img/cowMilk.png";
import buffaloMilk from "../../img/buffaloMilk.png";
import familyPack from "../../img/familyPack.png";
import butterMilk from "../../img/plainChach.png";
import masalaChach from "../../img/masalaChach.png";
import slimCurd from "../../img/dahiLight.png";
import Curd from "../../img/curd.png";
import a2DesiCowGhee from "../../img/a2CowGhee.png";
import buffaloGhee from "../../img/buffaloGhee.png";

const allProductsDetail = {
  a2DesiCowMilk: {
    img: a2DesiCowMilk,
    category: "Milk",
    heading: "A2 Desi Cow Milk",
    info: "A2 Desi cow milk from Vardaan Farms is pure, fresh, and natural. Our cows are well-cared for and graze on lush pastures. This milk is easy to digest and packed with nutrients. Enjoy it in your tea, coffee, or straight from the glass. Vardaan Farms brings the goodness of nature to your doorstep.",
    availableIn: ["500 ml"],
    nutritionalFact: {
      Energy: "84.88",
      TotalFat: "4.2",
      saturatedFat: "2.29",
      transFat: "0",
      cholestrol: "7.02",
      carbohydrate: "8.42",
      totalSugar: "8.42",
      addedSugar: "0",
      protein: "3.35",
      sodium: "49.32",
      calcium: "136.48",
    },
    measurmentUnit: "ml",
    color: "#b04226",
  },
  fullCream: {
    img: fullCream,
    category: "Milk",
    heading: "Full Cream Milk",
    info: "Vardaan Farms' full cream milk is rich and creamy, perfect for those who love a hearty taste. Our cows are fed a natural diet, ensuring the milk is wholesome. Use it to make delicious desserts, smoothies, or just enjoy a glass. Experience the quality and care in every sip from Vardaan Farms.",
    availableIn: ["400ml","500 ml","6 l"],
    nutritionalFact: {
      Energy: "87",
      TotalFat: "6.0",
      saturatedFat: "3.8",
      transFat: "0.0",
      cholestrol: "16",
      carbohydrate: "5.0",
      totalSugar: "5.0",
      addedSugar: "0.0",
      protein: "3.2",
      sodium: "42",
      calcium: "120",
    },
    measurmentUnit: "ml",
    color: "#e50000",
  },
  tonedMilk: {
    img: tonedMilk,
    category: "Milk",
    heading: "Toned Milk",
    info: "Toned milk from Vardaan Farms is a great choice for those who want a lighter option. It retains all the essential nutrients while being lower in fat. Ideal for making your morning cereal, coffee, or tea, it also works well in various recipes. Taste the balance of health and flavor with every drop from Vardaan Farms.",
    availableIn: ["400ml","500 ml"],
    nutritionalFact: {
      Energy: "58",
      TotalFat: "3.0",
      saturatedFat: "2.0",
      transFat: "0.0",
      cholestrol: "8.0",
      carbohydrate: "4.7",
      totalSugar: "4.7",
      addedSugar: "0.0",
      protein: "3.0",
      sodium: "40",
      calcium: "110",
    },
    measurmentUnit: "ml",
    color: "#10807a",
  },
  doubleTonedMilk: {
    img: doubleTonedMilk,
    category: "Milk",
    heading: "Double Toned Milk",
    info: "Vardaan Farms' double toned milk offers a healthy option for those watching their fat intake. It has all the essential nutrients while being light and refreshing. Perfect for making tea, coffee, or enjoying a chilled glass. Bring the freshness and quality of Vardaan Farms into your home.",
    availableIn: [ "170 ml", "400 ml","500 ml"],
    nutritionalFact: {
      Energy: "46",
      TotalFat: "1.5",
      saturatedFat: "1.0",
      transFat: "0.0",
      cholestrol: "4.0",
      carbohydrate: "5.0",
      totalSugar: "5.0",
      addedSugar: "0.0",
      protein: "3.2",
      sodium: "42",
      calcium: "120",
    },
    measurmentUnit: "ml",
    color: "#40267b",
  },
  naturalCowMilk: {
    img: naturalCowMilk,
    category: "Milk",
    heading: "Natural Cow Milk",
    info: "Vardaan Farms' natural cow milk is fresh and pure, straight from our well-cared-for cows. This milk is packed with natural nutrients and has a rich, authentic taste. Perfect for your daily needs, it can be enjoyed in many ways, from drinking a glass to using it in recipes. Trust in the quality and care of Vardaan Farms.",
    availableIn: ["350 ml","500 ml"],
    nutritionalFact: {
      Energy: "67",
      TotalFat: "4.0",
      saturatedFat: "2.4",
      transFat: "0.0",
      cholestrol: "12",
      carbohydrate: "4.7",
      totalSugar: "4.7",
      addedSugar: "0.0",
      protein: "3.0",
      sodium: "44",
      calcium: "110",
    },
    measurmentUnit: "ml",
    color: "#216da6",
  },
  buffaloMilk: {
    img: buffaloMilk,
    category: "Milk",
    heading: "Buffalo Milk",
    info: "Buffalo milk from Vardaan Farms is thick, creamy, and full of essential nutrients. Ideal for making rich and delicious dairy products, it adds a special touch to your recipes. Our buffaloes are raised with care, ensuring high-quality milk. Experience the richness of buffalo milk from Vardaan Farms in every glass.",
    availableIn: ["500 ml", "1 L"],
    nutritionalFact: {
      Energy: "91",
      TotalFat: "6.5",
      saturatedFat: "4",
      transFat: "0.0",
      cholestrol: "16",
      carbohydrate: "5",
      totalSugar: "5",
      addedSugar: "0.0",
      protein: "3.2",
      sodium: "50",
      calcium: "150",
    },
    measurmentUnit: "ml",
    color: "black",
  },
  familyPack: {
    img: familyPack,
    category: "Milk",
    heading: "Family Pack",
    info: "Vardaan Farms' family pack offers 100% fresh and natural milk, specially homogenized for your family's needs. It's perfect for daily use, ensuring everyone gets the essential nutrients in each glass. Enjoy the quality and purity of Vardaan Farms' milk in a convenient family pack.",
    availableIn: ["450 ml"],
    nutritionalFact: {
      Energy: "74.1",
      TotalFat: "4.5",
      saturatedFat: "2.8",
      transFat: "0.0",
      cholestrol: "12",
      carbohydrate: "5.1",
      totalSugar: "5.1",
      addedSugar: "0.0",
      protein: "3.3",
      sodium: "45",
      calcium: "150",
    },
    measurmentUnit: "ml",
    color: "#bd0014",
  },
  butterMilk: {
    img: butterMilk,
    category: "Chach",
    heading: "Butter Milk",
    info: "Vardaan Farms' plain buttermilk is light and refreshing, perfect for staying cool and hydrated. It's made from our pure, natural milk and has a tangy taste that's delightful on its own or used in cooking. Enjoy this healthy and tasty drink, knowing it's made with care at Vardaan Farms.",
    availableIn: ["300 ml"],
    nutritionalFact: {
      Energy: "23",
      TotalFat: "0.7",
      saturatedFat: "0.4",
      transFat: "0.0",
      cholestrol: "2",
      carbohydrate: "2.5",
      totalSugar: "2.5",
      addedSugar: "0.0",
      protein: "1.3",
      sodium: "30",
      calcium: "52",
    },
    measurmentUnit: "ml",
    color: "#024122",
  },
  masalaChach: {
    img: masalaChach,
    category: "Chach",
    heading: "Masala Chach",
    info: "Masala chach from Vardaan Farms is a refreshing and flavorful drink, made from our natural milk and a blend of spices. It's perfect for cooling down on hot days and aiding digestion. Enjoy it as a tasty and healthy beverage option, crafted with care and quality at Vardaan Farms.",
    availableIn: ["300 ml"],
    nutritionalFact: {
      Energy: "20",
      TotalFat: "1.2",
      saturatedFat: "0.8",
      transFat: "0.0",
      cholestrol: "1.4",
      carbohydrate: "1.2",
      totalSugar: "1.2",
      addedSugar: "0.0",
      protein: "1.2",
      sodium: "263.1",
      calcium: "52",
    },
    measurmentUnit: "ml",
    color: "#539f14",
  },
  slimCurd: {
    img: slimCurd,
    category: "Curd",
    heading: "Slim Curd",
    info: "Vardaan Farms' slim curd is perfect for those seeking a low-fat, nutritious option. Made from our pure, natural milk, this curd is light and creamy, yet packed with essential nutrients. Enjoy it as a healthy snack or add it to your meals for a delicious touch. Taste the care and quality in every spoonful from Vardaan Farms.",
    availableIn: ["160 gm","400 gm", "5 kg", "15 kg"],
    nutritionalFact: {
      Energy: "40",
      TotalFat: "0.5",
      saturatedFat: "0.0",
      transFat: "0.0",
      cholestrol: "1.3",
      carbohydrate: "4.5",
      totalSugar: "4.5",
      addedSugar: "0.0",
      protein: "4.3",
      sodium: "48",
      calcium: "165",
    },
    measurmentUnit: "gm",
    color: "#56b5bc",
  },
  curd: {
    img: Curd,
    category: "Curd",
    heading: "Curd",
    info: "Vardaan Farms' curd is rich, creamy, and made from our pure, natural milk. It's packed with essential nutrients and has a smooth texture that enhances any meal. Enjoy it as a refreshing snack or add it to your recipes for a delightful touch. Experience the quality and care in every spoonful from Vardaan Farms.",
    availableIn: ["400 gm"],
    nutritionalFact: {
      Energy: "62",
      TotalFat: "3",
      saturatedFat: "2.1",
      transFat: "0.0",
      cholestrol: "3.4",
      carbohydrate: "5",
      totalSugar: "5",
      addedSugar: "0.0",
      protein: "3.7",
      sodium: "47.6",
      calcium: "168",
    },
    measurmentUnit: "gm",
    color: "#ed4500",
  },
  a2DesiCowGhee: {
    img: a2DesiCowGhee,
    category: "Ghee",
    heading: "A2 Desi Cow Ghee",
    info: "Vardaan Farms' A2 Desi cow ghee is made from the milk of well-cared-for cows. This ghee is rich in flavor and nutrients, perfect for cooking or adding to your meals. Enjoy the pure, traditional taste and health benefits of our A2 Desi cow ghee, crafted with care and quality at Vardaan Farms.",
    availableIn: ["500 ml","1 L"],
    nutritionalFact: {
      Energy: "897",
      caloriesFromFat: "897",
      totalFat:"99.72",
      saturatedFatyAcid: "66.71",
      mufa:"26.67",
      pufa:"2.94",
      cholestrol: "159",
      carbohydrate: "<1",
      totalSugar: "0",
      protein: "<0.5",
    },
    measurmentUnit: "gm",
    color: "#dbb234",
  },
  buffaloGhee: {
    img: buffaloGhee,
    category: "Ghee",
    heading: "Buffalo Ghee",
    info: "Buffalo ghee from Vardaan Farms is rich and flavorful, perfect for adding depth to your cooking. Made from the milk of well-cared-for buffaloes, it retains all the essential nutrients. Use it in your recipes or enjoy its taste in traditional dishes. Experience the quality and care in every spoonful of Vardaan Farms' buffalo ghee.",
    availableIn: ["500 ml", "1 L"],
    nutritionalFact: {
      Energy: "897.39",
      caloriesFromFat: "897.39",
      totalFat:"99.71",
      saturatedFatyAcid: "66.71",
      mufa:"26.67",
      pufa:"2.94",
      cholestrol: "159",
      carbohydrate: "<1",
      totalSugar: "0",
      protein: "<0.5",
    },
    measurmentUnit: "gm",
    color: "#4a3523",
  },
};

export default allProductsDetail;
