import a2DesiCowMilk from "../../img/a2DesiCowMilk.png";
import fullCream from "../../img/fullCream.png";
import tonedMilk from "../../img/tonedMilk.png";
import doubleTonedMilk from "../../img/DTM2.png";
import naturalCowMilk from "../../img/cowMilk.png";
import buffaloMilk from "../../img/buffaloMilk.png";
import familyPack from "../../img/familyPack.png";
import butterMilk from "../../img/plainChach.png";
import masalaChach from "../../img/masalaChach.png";
import slimCurd from "../../img/dahiLight.png";
import Curd from "../../img/curd.png";
import a2DesiCowGhee from "../../img/a2CowGhee.png";
import buffaloGhee from "../../img/buffaloGhee.png";

const allProductsDetail = {
  a2DesiCowMilk: {
    img: a2DesiCowMilk,
    category: "Milk",
    heading: "A2 Desi Cow Milk",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"ml",
    color:"#b04226",

  },
  fullCream: {
    img: fullCream,
    category: "Milk",
    heading: "Full Cream Milk",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
     "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"ml",
    color:"#e50000",
  },
  tonedMilk: {
    img: tonedMilk,
    category: "Milk",
    heading: "Toned Milk",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"ml",
    color:"#10807a",
  },
  doubleTonedMilk: {
    img: doubleTonedMilk,
    category: "Milk",
    heading: "Double Toned Milk",
    info: "",
    availableIn: ["500 ml", "170 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"ml",
    color:"#40267b",
  },
  naturalCowMilk: {
    img: naturalCowMilk,
    category: "Milk",
    heading: "Natural Cow Milk",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"ml",
    color:"#216da6",
  },
  buffaloMilk: {
    img: buffaloMilk,
    category: "Milk",
    heading: "Buffalo Milk",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"ml",
    color:"black",
  },
  familyPack: {
    img: familyPack,
    category: "Milk",
    heading: "Family Pack",
    info: "",
    availableIn: ["450 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"ml",
    color:"#bd0014",
  },
  butterMilk: {
    img: butterMilk,
    category: "Chach",
    heading: "Butter Milk",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"ml",
    color:"#024122",
  },
  masalaChach: {
    img: masalaChach,
    category: "Chach",
    heading: "Masala Chach",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
     "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"ml",
    color:"#539f14",
  },
  slimCurd: {
    img: slimCurd,
    category: "Curd",
    heading: "Slim Curd",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"gm",
    color:"#56b5bc",
  },
  curd: {
    img: Curd,
    category: "Curd",
    heading: "Curd",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"gm",
    color:"#ed4500",
  },
  a2DesiCowGhee: {
    img: a2DesiCowGhee,
    category: "Ghee",
    heading: "A2 Desi Cow Ghee",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"gm",
    color:"#dbb234",
  },
  buffaloGhee: {
    img: buffaloGhee,
    category: "Ghee",
    heading: "Buffalo Ghee",
    info: "",
    availableIn: ["500 ml"],
    nutritionalFact: {
      "Energy": "" ,
      "TotalFat": "" ,
      "saturatedFat": "" ,
      "transFat": "" ,
      "cholestrol": "" ,
      "carbohydrate": "" ,
      "totalSugar": "" ,
      "addedSugar": "" ,
      "protein": "" ,
      "sodium": "" ,
      "calcium": "" ,
    },
    measurmentUnit:"gm",
    color:"#4a3523",
  },
};

export default allProductsDetail;
